# .gitlab-ci.yml
image: docker:20.10.16

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_TLS_CERTDIR: ""
  PYTHON_VERSION: "3.13"

services:
  - name: docker:20.10.16-dind
    pull_policy: if-not-present

stages:
  - build

docker-build:
  stage: build
  before_script:
    - echo "$CI_PERSONAL_ACCESS_TOKEN" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - |
      # Build using the Dockerfile
      docker build -f Dockerfile -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG \
        -t $DOCKER_IMAGE_NAME:latest \
        --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_IMAGE_NAME:latest
  only:
    - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .docker/cache
